### ISSUE TITLE
Broker should reject another request with status code 422 when a synchronous operation is incomplete

### ISSUE THREAD

**Issue by liu-sheng** [huaweicloud/huaweicloud-service-broker#53]
According to ref[1], Broker should reject another request with status code 422 when a synchronous operation is incomplete. Currently, huaweicloud-service-broker will return `500` status code if a service instance provisioned asynchronously and then perform updating or deletion operations. see:

```
should accept a valid update request
Error: expected 202 "Accepted", got 500 "Internal Server Error"
    at Test._assertStatus (node_modules/supertest/lib/test.js:268:12)
    at Test._assertFunction (node_modules/supertest/lib/test.js:283:11)
    at Test.assert (node_modules/supertest/lib/test.js:173:18)
    at assert (node_modules/supertest/lib/test.js:131:12)
    at /home/zuul/src/github.com/openservicebrokerapi/osb-checker/2.13/tests/node_modules/supertest/lib/test.js:128:5
    at Test.Request.callback (node_modules/superagent/lib/node/index.js:718:3)
    at parser (node_modules/superagent/lib/node/index.js:906:18)
    at IncomingMessage.res.on (node_modules/superagent/lib/node/parsers/json.js:19:7)
    at endReadableNT (_stream_readable.js:1085:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

[1] https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/spec.md#asynchronous-operations

**Comment by edisonxiang** [comment]
Thanks
This issue has already been resolved.
So close it.
